### ISSUE TITLE
Time selector not working on mobile

### ISSUE THREAD

**Issue by anzgar01** [Stellarium/stellarium-web-engine#81]
Hi,
when pointing on the time selector (bottom right) on mobile devices (tested on android chrome and ios safari), the popup to select the time opens up just fine, but there seems to be no way to close it.
Pointing elsewhere doesn't close it, and there is not button to close it either. Pointing on the clock symbol again also doesn't work.
Can you please fix this?
Thanks a lot in advance

**Comment by xalioth** [comment]
Hi,
could you please try again? We fixed some issues yesterday on iOS.

**Comment by anzgar01** [comment]
Sure.
Tested again (assuming stellarium-web.org is on the latest version), but sadly still not working on both Android an iOS.
Or should I download the latest version myself an test locally?

**Comment by anzgar01** [comment]
One addition:
clicking on the clock symbol seems to be breaking something.
Usually if you click on a star, the popup with the information for that star can be closed by clicking on the "x" in the upper right corner. If you click on the clock symbol, and then on a star (the time selection still open as described above), the popup with the information for the star opens up, but can't be closed using the "x".
Clicking somewhere else in the "sky" does close the information window, the clock / time window stays open.

So there is some influence from the clock/time part to other parts of the software. some event handler maybe?

**Comment by retroj** [comment]
I can confirm. I see this behavior on an iPad 8th generation with Safari, and in Firefox on an Android device. This makes Stellarium-web all but unusable on mobile.

**Comment by abluetuba** [comment]
Hi! I think I identified the issue in the `date-time-picker` component:
```javascript
window.addEventListener('touchend', function (event) {
  that.stopIncTime()
  event.preventDefault()
})
```
```event.preventDefault()``` basically cancels every touch input after the component is mounted: deleting this seems to fix the problem.

Also this listener remains active even after the component is closed (since it is attached to the `window`): maybe adding something like `@touchend="stopIncTime()"` directly to the buttons instead would be more efficient.

I can gladly take a closer look at it if that's ok :)

**Comment by xalioth** [comment]
Hey thanks for the tip, I'm having a look at it!

**Comment by anzgar01** [comment]
Hello Fabien,and first of all merry christmas to you!!  :-)I found a modified copy of stellarium-Web at software.star-register.com, which I assume was modified by you?I really like they "ar" type of modification, where an arrow is displayed to show the stars location, and then the mobile device is moved to get there.Could you tell me what the price would be for this kind of extension, and whether you would be able and willing to do that for me as well?Thanks a lot in advanceAnsgarP.S.: I am sadly still not making money with my site, but am close to getting break even at least  :-)Am 20.08.2021 13:55 schrieb Fabien Chereau ***@***.***>:
Hey thanks for the tip, I'm having a look at it!

**Comment by xalioth** [comment]
Hi, we didn't do the arrow part of the code, they did that themselves, please contact us per email for more info!

Regarding this ticket, I think this issue should be solved by now, let me know if it's OK for you now.
